# SQLite version 3.x
#   gem install postgresl
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresl'

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: ckyony
  password:
  database: grain-dev

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: ckyony
  database: grain-test
  password:


